apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-container
        image: 189326461630.dkr.ecr.us-east-1.amazonaws.com/hello-devops:latest
        ports:
        - containerPort: 5000

